/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('./src/components/common/AButton.vue')['default']
    ADate: typeof import('./src/components/common/ADate.vue')['default']
    AInput: typeof import('./src/components/common/AInput.vue')['default']
    APassword: typeof import('./src/components/common/APassword.vue')['default']
    APhone: typeof import('./src/components/common/APhone.vue')['default']
    ASelect: typeof import('./src/components/common/ASelect.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    BBreadcrumb: typeof import('./src/components/common/BBreadcrumb.vue')['default']
    BDialog: typeof import('./src/components/common/BDialog.vue')['default']
    BDrawer: typeof import('./src/components/common/BDrawer.vue')['default']
    BEmoji: typeof import('./src/components/common/BEmoji.vue')['default']
    BMultiSelect: typeof import('./src/components/common/BMultiSelect.vue')['default']
    BTable: typeof import('./src/components/common/BTable.vue')['default']
    BTime: typeof import('./src/components/common/BTime.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chart: typeof import('primevue/chart')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EFooter: typeof import('./src/components/layout/EFooter.vue')['default']
    ENavBar: typeof import('./src/components/layout/ENavBar.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
