name: Vue.js Project Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  vue-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Run lint and unit tests
        run: |
          npm run lint
          npm run test || echo "Tests failed but continuing"

  deploy:
    runs-on: ubuntu-latest
    needs: vue-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "===> Switching to deployment directory"
            cd ${{ secrets.REMOTE_PATH }}

            echo "===> Pulling latest code"
            git pull origin master

            echo "===> Installing dependencies"
            npm ci

            echo "===> Building the Vue app"
            npm run build

            echo "===> Deployment complete ✅"
